name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish NET6.WebAPI/NET6.WebAPI.csproj -c Release -o webapi

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: webapi
        path: webapi/**
        if-no-files-found: error

  deploy_test:
    needs: build
    runs-on: self-hosted
    env:
      app-name: 'webapi'
      app-pool-name: 'pool-webapi'
      physical-path: 'C:\deployments\webapi'
      PROJECT_DIRECTORY_PATH: 'NET6.WebAPI'
      IIS_SERVER_COMPUTER_NAME: 'FINCOAD'
      IIS_WEBSITE_NAME: 'Default Web Site'
      IIS_SERVER_USERNAME: ''
      IIS_SERVER_PASSWORD: ''
      RECYCLE_APP_NAME: 'webapi'
      WEBSITE_CONTENT_PATH: 'D:\deployments\webapi'

    environment:
      name: Test

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: webapi
        path: '${{ env.physical-path }}'

    - name: Stop Application Pool
      shell: cmd
      run: "C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:recycleApp -dest:'recycleApp="Default Web Site/webapi"','recycleMode="StopAppPool"'

    - name: Deploy Application
      shell: cmd
      run: "C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:'iisApp="C:\deployments\webapi"' -dest:'iisApp="Default Web Site/webapi"'

    - name: Start Application Pool
      shell: cmd
      run: "C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:recycleApp -dest:'recycleApp="Default Web Site/webapi"','recycleMode="StartAppPool"'